typedef struct {
  PetscScalar         mu;   
  PetscInt Nv;              
  PetscInt Nv_U;            
  PetscInt Nv_P;            
  PetscInt N_P_total_loc;   
  PetscInt N_U_total_loc;  
  PetscInt N_V_total_glo;  
  PetscInt N_V_total_loc;  
  PetscInt N_V_inter_loc;  
  PetscInt N_V_bound_loc;  
  PetscInt N_V_ghost_loc;  
  PetscInt N_V_diric_loc;  
  PetscInt N_V_neuma_loc;  
  PetscInt N_V_robin_loc;  
  PetscInt N_V_unkno_loc;  
  PetscInt N_V_U_total_glo; 
  PetscInt N_V_P_total_glo; 
  PetscInt N_V_U_total_loc; 
  PetscInt N_V_P_total_loc; 
  PetscInt N_V_U_diric_loc; 
  PetscInt N_V_P_diric_loc; 
  PetscInt     **GI_V;        
  PetscInt      *GI_V_ghost;   
  PetscInt       GI_V_start;   
  PetscInt       GI_V_P_start; 
  PetscInt      N_Gr;
  FLUID_BC_TYPE  **Gr_bound_type;   
  PetscScalar    **Gr_bound_value;  
  PetscScalar    **Gr_bound_value2; 
  PetscInt *GI_V_U_bound_dir; 
  PetscInt *GI_V_P_bound_dir; 
  PetscInt *GI_V_U_non_dir;   
  PetscInt *GI_V_P_non_dir;   
  FLUID_VISCOSITY_METHOD     ViscMethod; 
  PetscScalar         mu2;        
  PetscScalar     A, B, C;        
  PetscScalar     Bd, Bv;         

} StokesVariables_Struct; 